[supervisord]
nodaemon=true
user=root

[program:backend]
command=gunicorn arayuz:app --bind 0.0.0.0:%(ENV_PORT)s --workers 2 --threads 4 --timeout 60
autostart=true
autorestart=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0

