[supervisord]
nodaemon=true
user=root

[program:backend]
command=gunicorn arayuz:app --bind 127.0.0.1:5000 --workers 2 --threads 4 --timeout 60
autostart=true
autorestart=true

[program:frontend]
command=npx next start --port %(ENV_PORT)s
autostart=true
autorestart=true

